#ifndef AIOS_SHELL_INTENT_H_
#define AIOS_SHELL_INTENT_H_

#include "core/types.h"

typedef enum {
    INTENT_CLEAR = 0,
    INTENT_MEMINFO = 1,
    INTENT_CPUINFO = 2,
    INTENT_SELFTEST = 3,
    INTENT_DISKINFO = 4,
    INTENT_MODELINFO = 5,
    INTENT_CALC = 6,
    INTENT_SCREENTEST = 7,
    INTENT_HELP = 8,
    INTENT_ABOUT = 9,
    INTENT_REBOOT = 10,
    INTENT_SHUTDOWN = 11,
    INTENT_FALLBACK = 12
} intent_id_t;

#define INTENT_COUNT 13u

STATIC_ASSERT(INTENT_CLEAR == 0);
STATIC_ASSERT(INTENT_MEMINFO == 1);
STATIC_ASSERT(INTENT_CPUINFO == 2);
STATIC_ASSERT(INTENT_SELFTEST == 3);
STATIC_ASSERT(INTENT_DISKINFO == 4);
STATIC_ASSERT(INTENT_MODELINFO == 5);
STATIC_ASSERT(INTENT_CALC == 6);
STATIC_ASSERT(INTENT_SCREENTEST == 7);
STATIC_ASSERT(INTENT_HELP == 8);
STATIC_ASSERT(INTENT_ABOUT == 9);
STATIC_ASSERT(INTENT_REBOOT == 10);
STATIC_ASSERT(INTENT_SHUTDOWN == 11);
STATIC_ASSERT(INTENT_FALLBACK == 12);
STATIC_ASSERT(INTENT_COUNT == 13u);

#endif  /* AIOS_SHELL_INTENT_H_ */
